"use client";

import { useEffect, useId, useRef, type KeyboardEvent, type ReactNode, type RefObject } from "react";

type Props = { open: boolean; title: string; description?: string; children: ReactNode; footer: ReactNode; maxWidth?: string; initialFocusRef?: RefObject<HTMLElement | null>; onClose: () => void };

export function PostActionDialogShell({ open, title, description, children, footer, maxWidth = "max-w-[720px]", initialFocusRef, onClose }: Props) {
  const titleId = useId(); const panelRef = useRef<HTMLElement>(null); const headingRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => { if (!open) return; const trigger = document.activeElement instanceof HTMLElement ? document.activeElement : null; const overflow = document.body.style.overflow; document.body.style.overflow = "hidden"; (initialFocusRef?.current ?? headingRef.current)?.focus(); const escape = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", escape); return () => { window.removeEventListener("keydown", escape); document.body.style.overflow = overflow; if (trigger?.isConnected) trigger.focus(); }; }, [open, onClose, initialFocusRef]);
  if (!open) return null;
  function trap(event: KeyboardEvent<HTMLElement>) { if (event.key !== "Tab") return; const nodes = panelRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href], [tabindex]:not([tabindex="-1"])'); if (!nodes?.length) return event.preventDefault(); const first = nodes.item(0); const last = nodes.item(nodes.length - 1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }
  return <div role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()} className="fixed inset-0 z-[95] flex items-center justify-center overflow-y-auto bg-[#071b33]/60 p-2 backdrop-blur-[2px] sm:p-5"><section ref={panelRef} role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={trap} onMouseDown={(event) => event.stopPropagation()} className={`my-auto flex max-h-[calc(100dvh-1rem)] w-full ${maxWidth} flex-col overflow-hidden rounded-xl border border-[#bfd3f2] bg-white shadow-[0_24px_80px_rgba(7,27,51,.28)] sm:max-h-[calc(100dvh-2.5rem)]`}><header className="flex shrink-0 items-start justify-between gap-4 border-b border-[#d3e4fe] px-4 py-4 sm:px-6"><div><h2 ref={headingRef} tabIndex={-1} id={titleId} className="text-xl font-extrabold outline-none sm:text-2xl">{title}</h2>{description && <p className="mt-1 text-sm leading-6 text-[#657080]">{description}</p>}</div><button type="button" aria-label={`Close ${title}`} onClick={onClose} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg border border-[#c8d8ef] text-xl outline-none hover:bg-[#eff4ff] focus-visible:ring-2 focus-visible:ring-[#0058bc]">×</button></header><div className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden p-4 sm:p-6">{children}</div><footer className="flex shrink-0 flex-wrap justify-end gap-3 border-t border-[#d3e4fe] bg-[#f8faff] px-4 py-4 sm:px-6">{footer}</footer></section></div>;
}
