"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CalendarWorkspaceHeader } from "@/components/calendar/calendar-workspace-header";
import { CalendarWorkspaceShell } from "@/components/calendar/calendar-workspace-shell";
import { GeneratedPostMockupDialog } from "@/components/calendar/generated-post-mockup-dialog";
import { PostActionDialogShell } from "@/components/calendar/post-action-dialog-shell";
import { PostDraftCard } from "@/components/calendar/post-draft-card";
import { PostDraftPreviewDrawer } from "@/components/calendar/post-draft-preview-drawer";
import { PostDraftToolbar } from "@/components/calendar/post-draft-toolbar";
import { activeManualPostPermissions } from "@/lib/calendar/manual-post-permissions";
import { filterAndSortManualPosts, type ManualPostFilters } from "@/lib/calendar/manual-post-selectors";
import { approveManualPost, readManualPostResult, requestManualPostChanges, saveManualPost, submitManualPost } from "@/lib/calendar/manual-post-store";
import type { ManualPostDraft } from "@/lib/calendar/manual-post-types";
import { isManualPostComplete } from "@/lib/calendar/manual-post-validation";

const initialFilters: ManualPostFilters = { search: "", brandId: "all", campaignId: "all", platform: "all", status: "open" };
const permissions = activeManualPostPermissions;

export function PostDraftList() {
  const [posts, setPosts] = useState<ManualPostDraft[]>([]); const [hydrated, setHydrated] = useState(false); const [loadError, setLoadError] = useState("");
  const [filters, setFilters] = useState(initialFilters); const [selectedId, setSelectedId] = useState<string>(); const [mockupPostId, setMockupPostId] = useState<string>(); const [message, setMessage] = useState("");
  const [requestingChanges, setRequestingChanges] = useState(false); const [note, setNote] = useState(""); const [noteError, setNoteError] = useState("");
  const visible = useMemo(() => filterAndSortManualPosts(posts, filters), [posts, filters]); const selected = posts.find((post) => post.id === selectedId); const mockupPost = posts.find((post) => post.id === mockupPostId);
  const brands = uniqueOptions(posts, "brandId", "brandName"); const campaigns = uniqueOptions(posts, "campaignId", "campaignName");
  useEffect(() => { let active = true; window.queueMicrotask(() => { if (!active) return; load(); const savedMessage = window.sessionStorage.getItem("post-draft-message"); if (savedMessage) { setMessage(savedMessage); window.sessionStorage.removeItem("post-draft-message"); } }); return () => { active = false; }; }, []);
  function load() { const result = readManualPostResult(window.localStorage); setPosts(result.posts); setLoadError(result.status === "error" ? result.message : ""); setHydrated(true); }
  function persist(post: ManualPostDraft, success: string) { saveManualPost(window.localStorage, post); setPosts((current) => [post, ...current.filter((item) => item.id !== post.id)]); setMessage(success); }
  function submit() { if (!permissions.canSubmit || !selected || selected.status !== "draft") return; if (!isManualPostComplete(selected)) return setMessage("Complete all required post and schedule fields before submitting."); persist(submitManualPost(selected, "Wanda"), "Post submitted for approval."); }
  function approve() { if (!permissions.canApprove || !selected || selected.status !== "pending_approval") return; if (!isManualPostComplete(selected)) return setMessage("A valid planned date, time, and platform are required before approval."); const approved = approveManualPost(selected, "Sarah Jenkins"); persist(approved, "Post approved, generated, and scheduled."); setSelectedId(undefined); setMockupPostId(approved.id); }
  function requestChanges() { if (!permissions.canRequestChanges || !selected || selected.status !== "pending_approval") return; if (!note.trim()) { setNoteError("A reason is required."); return; } persist(requestManualPostChanges(selected, "Sarah Jenkins", note.trim()), "Changes requested."); closeRequestChanges(); }
  function closeRequestChanges() { setRequestingChanges(false); setNote(""); setNoteError(""); }
  function openGeneratedMockup(postId: string) { setSelectedId(undefined); setMockupPostId(postId); }
  function closeGeneratedMockup() { const postId = mockupPostId; setMockupPostId(undefined); setSelectedId(postId); }
  if (!hydrated) return <CalendarWorkspaceShell header={<CalendarWorkspaceHeader variant="post-drafts" canCreate={permissions.canCreate} />}><section aria-labelledby="post-drafts-heading"><h2 id="post-drafts-heading" className="text-3xl font-extrabold">Post Drafts</h2><div role="status" className="mt-6 animate-pulse rounded-xl border bg-white p-6 motion-reduce:animate-none"><span className="sr-only">Loading post drafts</span><div className="h-6 w-48 rounded bg-slate-200" /><div className="mt-4 h-28 rounded bg-slate-100" /></div></section></CalendarWorkspaceShell>;
  if (loadError) return <CalendarWorkspaceShell header={<CalendarWorkspaceHeader variant="post-drafts" canCreate={permissions.canCreate} />}><section aria-labelledby="post-drafts-error-heading" role="alert" className="rounded-xl border border-rose-200 bg-white p-8 text-center"><h2 id="post-drafts-error-heading" className="text-xl font-extrabold">Post drafts could not be loaded</h2><p className="mt-2 text-sm text-[#657080]">The stored draft data is invalid or unavailable.</p><button type="button" onClick={load} className="mt-5 min-h-11 rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc] focus-visible:ring-offset-2">Retry</button></section></CalendarWorkspaceShell>;
  return <><CalendarWorkspaceShell header={<CalendarWorkspaceHeader variant="post-drafts" canCreate={permissions.canCreate} />}><section aria-labelledby="post-drafts-heading"><header><h2 id="post-drafts-heading" className="text-3xl font-extrabold">Post Drafts</h2><p className="mt-2 text-sm text-[#657080]">Review, edit, and approve posts before they are added to the Calendar.</p><p className="mt-2 text-xs font-bold text-[#0058bc]">{posts.length} post{posts.length === 1 ? "" : "s"}</p></header>
    {message && <p role="status" className="mt-5 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-900">{message}</p>}<PostDraftToolbar filters={filters} brands={brands} campaigns={campaigns} onChange={setFilters} />
    {visible.length ? <div className="mt-6 grid gap-4 lg:grid-cols-2">{visible.map((post) => <PostDraftCard key={post.id} post={post} permissions={permissions} onPreview={(id) => { setSelectedId(id); setMessage(""); }} />)}</div> : <section className="mt-6 rounded-xl border border-dashed border-[#c5d2e5] bg-white p-10 text-center"><h3 className="text-lg font-extrabold">{posts.length ? "No post drafts match these filters" : "No post drafts yet"}</h3><p className="mt-2 text-sm text-[#657080]">{posts.length ? "Try changing the search or filter selection." : "Create a post and save it as a draft to review it here."}</p>{!posts.length && permissions.canCreate && <Link href="/calendar?createPost=1" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white">Create Post</Link>}</section>}
  </section></CalendarWorkspaceShell><PostDraftPreviewDrawer post={selected} permissions={permissions} onClose={() => setSelectedId(undefined)} onSubmit={submit} onApprove={approve} onRequestChanges={() => setRequestingChanges(true)} onViewGenerated={openGeneratedMockup} />{mockupPost && <GeneratedPostMockupDialog key={mockupPost.id} post={mockupPost} onClose={closeGeneratedMockup} />}{requestingChanges && <PostActionDialogShell open title="Request Changes" description={selected?.idea.title} onClose={closeRequestChanges} footer={<><button type="button" onClick={closeRequestChanges} className="min-h-11 rounded-lg border px-4 font-bold">Cancel</button><button type="button" onClick={requestChanges} className="min-h-11 rounded-lg bg-rose-700 px-4 font-bold text-white">Request Changes</button></>}><label htmlFor="post-change-note" className="text-sm font-bold">Reason</label><textarea id="post-change-note" rows={5} value={note} onChange={(event) => { setNote(event.target.value); setNoteError(""); }} aria-invalid={Boolean(noteError)} aria-describedby={noteError ? "post-change-note-error" : undefined} className="mt-2 w-full rounded-lg border p-3" />{noteError && <p id="post-change-note-error" role="alert" className="mt-2 text-sm font-bold text-rose-700">{noteError}</p>}</PostActionDialogShell>}</>;
}
function uniqueOptions(posts: ManualPostDraft[], idKey: "brandId" | "campaignId", nameKey: "brandName" | "campaignName") { return Array.from(new Map(posts.flatMap((post) => post.idea[idKey] ? [[post.idea[idKey]!, post.idea[nameKey] || post.idea[idKey]!]] : [])).entries()).map(([value, label]) => ({ value, label })); }
