"use client";

import Link from "next/link";
import { PostActionDialogShell } from "@/components/calendar/post-action-dialog-shell";
import { PostDraftStatusBadge } from "@/components/calendar/post-draft-status-badge";
import { formatAssetTypeLabel, formatPlatformLabel } from "@/lib/calendar/platform-options";
import type { ManualPostDraft, ManualPostPermissions } from "@/lib/calendar/manual-post-types";

export function PostDraftPreviewDrawer({ post, permissions, onClose, onSubmit, onApprove, onRequestChanges, onViewGenerated }: { post?: ManualPostDraft; permissions: ManualPostPermissions; onClose: () => void; onSubmit: () => void; onApprove: () => void; onRequestChanges: () => void; onViewGenerated: (postId: string) => void }) {
  if (!post) return null; const editable = permissions.canEdit && (post.status === "draft" || post.status === "changes_requested"); const calendarVersion = post.versions[0];
  const footer = <div className="flex w-full flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="min-h-11 rounded-lg border px-4 text-sm font-bold focus-visible:ring-2 focus-visible:ring-[#0058bc]">Close</button>{editable && <Link href={`/calendar?editDraft=${encodeURIComponent(post.id)}`} className="inline-flex min-h-11 items-center justify-center rounded-lg border border-[#0058bc] px-4 text-sm font-bold text-[#0058bc]">Edit</Link>}{post.status === "draft" && permissions.canSubmit && <button type="button" onClick={onSubmit} className="min-h-11 rounded-lg bg-[#0058bc] px-4 text-sm font-bold text-white">{post.changesRequestedAt ? "Resubmit for Approval" : "Submit for Approval"}</button>}{post.status === "pending_approval" && permissions.canRequestChanges && <button type="button" onClick={onRequestChanges} className="min-h-11 rounded-lg border border-rose-300 px-4 text-sm font-bold text-rose-700">Request Changes</button>}{post.status === "pending_approval" && permissions.canApprove && <button type="button" onClick={onApprove} className="min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-bold text-white">Approve, Generate and Schedule</button>}{post.status === "scheduled" && <button type="button" onClick={() => onViewGenerated(post.id)} className="min-h-11 rounded-lg border border-[#0058bc] px-4 text-sm font-bold text-[#0058bc] outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc]">View Generated Mockup</button>}{post.status === "scheduled" && calendarVersion && <Link href={`/calendar?post=${encodeURIComponent(calendarVersion.id)}`} className="inline-flex min-h-11 items-center justify-center rounded-lg bg-[#0058bc] px-4 text-sm font-bold text-white">View in Calendar</Link>}</div>;
  return <PostActionDialogShell open title={post.idea.title} description="Read-only post draft preview" onClose={onClose} footer={footer} maxWidth="max-w-[920px]"><div className="mb-5 flex flex-wrap items-center gap-3"><PostDraftStatusBadge status={post.status} />{post.status === "pending_approval" && !permissions.canApprove && <span className="text-sm font-semibold text-[#657080]">Awaiting approval</span>}</div>
    <dl className="grid gap-4 sm:grid-cols-2"><Info label="Campaign" value={post.idea.campaignName || post.idea.campaignId || "Not linked"} /><Info label="Brand" value={post.idea.brandName || "Not specified"} /><Info label="Creation Source" value="Manual" /><Info label="Content Pillar" value={post.idea.pillarId} /><Info label="Objective" value={formatAssetTypeLabel(post.idea.objective)} /><Info label="Target Audience" value={post.idea.targetAudience} /><Info label="Core Topic" value={post.idea.coreTopic} /><Info label="Owner" value={post.ownerName} /></dl>
    <div className="mt-6 grid gap-4">{post.versions.map((version) => <section key={version.id} className="rounded-xl border border-[#d3e4fe] bg-[#f8faff] p-4"><h3 className="font-extrabold text-[#0058bc]">{formatPlatformLabel(version.platform)}</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Content Type" value={formatAssetTypeLabel(version.assetType)} /><Info label="Headline" value={version.headline} /><Info label="Caption" value={version.caption} /><Info label="Visual Direction" value={version.visualBrief || "Not specified"} /><Info label="Planned Schedule" value={`${version.publishDate} at ${version.publishTime}`} /><Info label="Timezone" value={version.timezone} /></dl></section>)}</div>
    {post.approvalNote && <section className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-4"><h3 className="font-extrabold text-rose-900">Approval note</h3><p className="mt-2 text-sm text-rose-800">{post.approvalNote}</p></section>}
    <dl className="mt-6 grid gap-3 border-t pt-5 sm:grid-cols-2"><Info label="Created" value={formatDate(post.createdAt)} /><Info label="Updated" value={formatDate(post.updatedAt)} />{post.submittedAt && <Info label="Submitted" value={`${formatDate(post.submittedAt)} by ${post.submittedBy}`} />}{post.approvedAt && <Info label="Approved" value={`${formatDate(post.approvedAt)} by ${post.approvedBy}`} />}{post.status === "scheduled" && <Info label="Generated" value={formatDate(post.generatedAt ?? post.approvedAt ?? post.updatedAt)} />}</dl>
  </PostActionDialogShell>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs font-extrabold uppercase tracking-[.08em] text-[#8b96a5]">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm font-semibold">{value}</dd></div>; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Unavailable" : new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Jakarta" }).format(date); }
