"use client";

import { useRef, useState } from "react";
import { PostActionDialogShell } from "@/components/calendar/post-action-dialog-shell";
import { validatePlanningRange } from "@/lib/billing/entitlements";
import { workspaceSubscriptionMock } from "@/lib/billing/mock-data";
import { formatPlatformLabel } from "@/lib/calendar/platform-options";
import type { ContentIdea, ContentVersion } from "@/lib/calendar/types";

export type ReschedulePostPayload = { versionId: string; publishDate: string; publishTime: string; timezone: string };
export function ReschedulePostDialog({ open, version, idea, onClose, onSubmit }: { open: boolean; version?: ContentVersion; idea?: ContentIdea; onClose: () => void; onSubmit: (payload: ReschedulePostPayload) => void }) {
  const dateRef = useRef<HTMLInputElement>(null); const [date, setDate] = useState(version?.publishDate ?? ""); const [time, setTime] = useState(version?.publishTime ?? ""); const [errors, setErrors] = useState<Record<string, string>>({});
  if (!open) return null;
  function submit() { if (!version || version.status !== "scheduled") return; const next: Record<string, string> = {}; if (!date) next.date = "Publish date is required."; if (!time) next.time = "Publish time is required."; if (date) { const range = validatePlanningRange({ subscription: workspaceSubscriptionMock, startDate: date, endDate: date, referenceDate: "2026-07-15" }); if (!range.valid) next.date = range.message; } setErrors(next); if (next.date) return dateRef.current?.focus(); if (next.time) return document.getElementById("reschedule-time")?.focus(); onSubmit({ versionId: version.id, publishDate: date, publishTime: time, timezone: version.timezone || "Asia/Jakarta" }); }
  const footer = <><button type="button" onClick={onClose} className="rounded-lg border border-[#c5d2e5] bg-white px-5 py-2.5 text-sm font-bold outline-none hover:bg-[#eff4ff] focus-visible:ring-2 focus-visible:ring-[#0058bc]">Cancel</button><button type="button" disabled={!version} onClick={submit} className="rounded-lg bg-[#0058bc] px-5 py-2.5 text-sm font-bold text-white outline-none hover:bg-[#004493] focus-visible:ring-2 focus-visible:ring-[#0058bc] disabled:bg-[#a1a9b5]">Save Schedule</button></>;
  return <PostActionDialogShell open={open} title="Reschedule Post" description="Update the publish date and time without changing post content." initialFocusRef={dateRef} onClose={onClose} footer={footer} maxWidth="max-w-[520px]">{version?.status === "scheduled" ? <div className="grid gap-5"><section className="rounded-xl border border-[#d3e4fe] bg-[#f8faff] p-4"><p className="text-xs font-extrabold uppercase tracking-[.1em] text-[#0058bc]">{formatPlatformLabel(version.platform)}</p><h3 className="mt-2 break-words text-lg font-extrabold">{version.headline || idea?.title || "Untitled post"}</h3><p className="mt-2 text-sm text-[#657080]">{idea?.title ?? "Content idea unavailable"}</p><p className="mt-3 text-xs font-semibold text-[#657080]">Current: {version.publishDate} at {version.publishTime} · {version.timezone}</p></section><label><span className="mb-2 block text-xs font-extrabold uppercase tracking-[.1em] text-[#657080]">Publish Date</span><input ref={dateRef} type="date" value={date} onChange={(e) => { setDate(e.target.value); setErrors({}); }} aria-invalid={Boolean(errors.date)} className="h-11 w-full rounded-lg border border-[#c5d2e5] px-3 outline-none focus:ring-2 focus:ring-blue-100" />{errors.date && <span className="mt-1 block text-xs font-semibold text-rose-600">{errors.date}</span>}</label><label><span className="mb-2 block text-xs font-extrabold uppercase tracking-[.1em] text-[#657080]">Publish Time</span><input id="reschedule-time" type="time" value={time} onChange={(e) => { setTime(e.target.value); setErrors({}); }} aria-invalid={Boolean(errors.time)} className="h-11 w-full rounded-lg border border-[#c5d2e5] px-3 outline-none focus:ring-2 focus:ring-blue-100" />{errors.time && <span className="mt-1 block text-xs font-semibold text-rose-600">{errors.time}</span>}</label><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.1em] text-[#657080]">Timezone</p><p className="rounded-lg border border-[#d3e4fe] bg-[#f1f5f9] px-3 py-3 text-sm text-[#657080]">{version.timezone || "Asia/Jakarta"}</p></div></div> : <p role="status" className="rounded-xl bg-amber-50 p-5 text-sm font-bold text-amber-900">Only scheduled posts can be rescheduled.</p>}</PostActionDialogShell>;
}
