"use client";

import Image from "next/image";
import { BrandBrainDrawer } from "@/components/brand-brain/brand-brain-drawer";
import { interpretToneValue } from "@/components/brand-brain/tone-dial-mock-modal";
import type { BrandBrainState } from "@/lib/brand-brain/types";
import type { WorkspaceAsset } from "@/lib/assets/types";

export function BrandInsightsMockDrawer({ isOpen, libraryAssets, onClose, state }: { isOpen: boolean; libraryAssets: WorkspaceAsset[]; onClose: () => void; state: BrandBrainState }) {
  if (!isOpen) return null;
  const coreAssets = state.coreAssetIds.flatMap((id) => { const asset = libraryAssets.find((item) => item.id === id); return asset ? [asset] : []; }).slice(0, 3);
  const logoAsset = libraryAssets.find((asset) => asset.id === state.logoAssetId) ?? null;
  const sources = activeSources(state.analysis.sources);
  const scoreItems = [
    { label: "Voice Consistency", value: state.insights.voiceConsistency, description: "Your personality, communication style, and traits are clearly defined." },
    { label: "Tone Alignment", value: state.insights.toneAlignment, description: "Your selected tone balance provides a consistent writing direction." },
    { label: "Visual Readiness", value: state.insights.visualReadiness, description: "Your logo and core assets establish a recognizable visual identity." },
    { label: "Asset Quality", value: state.insights.assetQuality, description: "Your current brand assets are suitable for product and lifestyle content." },
  ];
  const coverage = [
    ["Brand Voice configured", Boolean(state.voice.primaryPersonality.trim() && state.voice.communicationStyle.trim()), "Configured", "Missing"],
    ["Tone Dial configured", Object.values(state.toneDial).every((value) => Number.isFinite(value) && value >= 0 && value <= 100), "Configured", "Missing"],
    ["Brand Logo configured", Boolean(logoAsset), "Configured", "Missing"],
    ["Core Brand Assets configured", coreAssets.length > 0, "Configured", "Missing"],
    ["Analysis Sources available", sources.length > 0, "Configured", "Missing"],
    ["Brand Analysis completed", state.analysis.status === "complete", "Complete", "Not analyzed"],
  ] as const;

  return <BrandBrainDrawer title="Brand Intelligence" description="Review how well your current brand data supports consistent AI-generated content." onClose={onClose} footer={<button type="button" onClick={onClose} className="h-11 rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white hover:bg-[#004493]">Close</button>}>
    <div className="grid gap-6 p-5 sm:p-7">
      <section className="rounded-xl border border-[#bfd3f2] bg-gradient-to-br from-[#eff4ff] to-white p-5 sm:p-6">
        <p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#0058bc]">Overall Brand Readiness</p>
        <div className="mt-3 flex flex-wrap items-end justify-between gap-3"><p className="text-5xl font-black tracking-[-.04em] text-[#0b1c30]">{state.insights.overallReadiness}%</p><ScoreStatus value={state.insights.overallReadiness} /></div>
        <ScoreProgress value={state.insights.overallReadiness} label="Overall Brand Readiness" />
        <p className="mt-4 text-sm leading-6 text-[#414755]">{readinessDescription(state.insights.overallReadiness)}</p>
      </section>

      <InsightSection title="Brand Intelligence Scores"><div className="grid gap-4 sm:grid-cols-2">{scoreItems.map((item) => <article key={item.label} className="rounded-xl border border-[#d3e4fe] bg-[#f8faff] p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-extrabold">{item.label}</h3><span className="text-lg font-black text-[#0058bc]">{item.value}%</span></div><ScoreProgress value={item.value} label={item.label} /><div className="mt-3"><ScoreStatus value={item.value} /></div><p className="mt-3 text-xs leading-5 text-[#657080]">{item.description}</p></article>)}</div></InsightSection>

      <InsightSection title="Brand Voice Summary"><div className="grid gap-4 sm:grid-cols-2"><SummaryCard label="Primary Personality" title={state.voice.primaryPersonality} description={state.voice.primaryPersonalityDescription} /><SummaryCard label="Communication Style" title={state.voice.communicationStyle} description={state.voice.communicationStyleDescription} /></div><div className="mt-4"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#657080]">Brand Traits</p>{state.voice.traits.length ? <div className="mt-2 flex flex-wrap gap-2">{state.voice.traits.map((trait) => <span key={trait} className="rounded-full bg-[#e1e0ff] px-3 py-1.5 text-xs font-bold text-[#4648d4]">#{trait}</span>)}</div> : <p className="mt-2 text-sm text-[#657080]">No brand traits have been defined.</p>}</div></InsightSection>

      <InsightSection title="Tone Summary"><div className="grid gap-4">{([{"key":"casualFormal","left":"Casual","right":"Formal"},{"key":"playfulSerious","left":"Playful","right":"Serious"},{"key":"conciseDetailed","left":"Concise","right":"Detailed"}] as const).map((tone) => { const value = state.toneDial[tone.key]; return <article key={tone.key} className="rounded-xl border border-[#d3e4fe] p-4"><div className="flex justify-between gap-4 text-xs font-extrabold uppercase tracking-[.1em] text-[#657080]"><span>{tone.left}</span><span>{tone.right}</span></div><div className="relative mt-3 h-2 rounded-full bg-[#e5eeff]"><span className="absolute top-1/2 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-white bg-[#0058bc] shadow" style={{ left: `clamp(8px, ${value}%, calc(100% - 8px))` }} /></div><div className="mt-3 flex justify-between text-sm font-bold"><span>{interpretToneValue(tone.key, value)}</span><span className="text-[#0058bc]">{value}</span></div></article>; })}</div></InsightSection>

      <InsightSection title="Visual Foundation"><div className="grid gap-5"><section className="rounded-xl border border-[#d3e4fe] p-4"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#657080]">Brand Logo</p>{logoAsset ? <div className="mt-3 flex items-center gap-4"><span className="flex h-20 w-20 shrink-0 items-center justify-center rounded-lg bg-[#f8faff] p-2"><Image src={logoAsset.previewUrl} width={72} height={72} unoptimized alt={logoAsset.name} className="max-h-full max-w-full object-contain" /></span><div className="min-w-0"><p className="truncate text-sm font-extrabold">{logoAsset.name}</p><p className="mt-1 text-xs text-[#657080]">Asset Library Logo</p><p className="mt-1 truncate text-xs text-[#717786]">{logoAsset.fileName}</p></div></div> : <p className="mt-2 text-sm text-[#657080]">No brand logo selected.</p>}</section><section><div className="flex justify-between gap-3"><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#657080]">Core Brand Assets</p><p className="text-xs font-bold text-[#0058bc]">{coreAssets.length} of 3 configured</p></div>{coreAssets.length ? <div className="mt-3 grid grid-cols-3 gap-3">{coreAssets.map((asset) => <article key={asset.id} className="min-w-0"><span className="relative block aspect-square overflow-hidden rounded-lg bg-[#eff4ff]"><Image src={asset.previewUrl} alt={asset.name} fill unoptimized className={asset.kind === "logo" ? "object-contain p-2" : "object-cover"} /></span><p className="mt-2 truncate text-xs font-extrabold">{asset.name}</p><p className="mt-1 truncate text-[10px] capitalize text-[#657080]">{asset.kind}</p></article>)}</div> : <p className="mt-3 text-sm text-[#657080]">No Core Brand Assets configured.</p>}{coreAssets.length > 0 && coreAssets.length < 3 ? <p className="mt-3 rounded-lg bg-amber-50 p-3 text-xs font-semibold text-amber-800">Select more Core Brand Assets from the central library.</p> : null}</section></div></InsightSection>

      <InsightSection title="Analysis Sources"><div className="flex items-center justify-between gap-3"><AnalysisBadge complete={state.analysis.status === "complete"} /><span className="text-xs font-semibold text-[#657080]">{sources.length} sources</span></div>{sources.length ? <dl className="mt-4 grid gap-3">{sources.map(([label, value]) => <div key={label} className="rounded-lg bg-[#f8faff] p-3"><dt className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#657080]">{label}</dt><dd className="mt-1 break-words text-sm font-semibold">{value}</dd></div>)}</dl> : <p className="mt-3 text-sm text-[#657080]">No brand sources have been analyzed yet.</p>}</InsightSection>

      <InsightSection title="Last Analysis"><p className="text-sm font-extrabold">{analysisStatusLabel(state.analysis.status)}</p>{state.analysis.lastAnalyzedAt ? <time dateTime={state.analysis.lastAnalyzedAt} className="mt-2 block text-sm text-[#657080]">{new Intl.DateTimeFormat(undefined, { dateStyle: "long", timeStyle: "short" }).format(new Date(state.analysis.lastAnalyzedAt))}</time> : <p className="mt-2 text-sm text-[#657080]">Brand analysis has not been run yet.</p>}<p className="mt-3 text-xs font-semibold text-[#0058bc]">Progress: {state.analysis.progress}% · Step {state.analysis.activeStep} of 5</p></InsightSection>

      <InsightSection title="Recommendations"><article className="rounded-xl border border-[#bfd3f2] bg-[#eff4ff] p-4"><h3 className="text-base font-extrabold text-[#0058bc]">{state.recommendation.title}</h3><p className="mt-2 text-sm leading-6 text-[#414755]">{state.recommendation.description}</p>{state.recommendation.items.length ? <ol className="mt-4 grid gap-2">{state.recommendation.items.slice(0, 3).map((item, index) => <li key={item} className="flex gap-3 rounded-lg bg-white/80 p-3 text-sm leading-5"><span className="font-extrabold text-[#0058bc]">{index + 1}</span><span>{item}</span></li>)}</ol> : null}</article></InsightSection>

      <InsightSection title="Data Coverage Summary"><div className="grid gap-2">{coverage.map(([label, configured, positive, negative]) => <div key={label} className="flex items-center justify-between gap-3 rounded-lg border border-[#d3e4fe] px-4 py-3"><span className="text-sm font-semibold">{label}</span><span className={`text-xs font-extrabold ${configured ? "text-emerald-700" : "text-[#8b96a5]"}`}>{configured ? `✓ ${positive}` : `○ ${negative}`}</span></div>)}</div></InsightSection>
    </div>
  </BrandBrainDrawer>;
}

function InsightSection({ children, title }: { children: React.ReactNode; title: string }) { return <section className="rounded-xl border border-[#d3e4fe] bg-white p-5"><h2 className="mb-4 text-lg font-extrabold tracking-[-.02em]">{title}</h2>{children}</section>; }
function SummaryCard({ description, label, title }: { description: string; label: string; title: string }) { return <article className="rounded-lg bg-[#f8faff] p-4"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#0058bc]">{label}</p><h3 className="mt-2 text-sm font-extrabold">{title}</h3><p className="mt-2 text-xs leading-5 text-[#657080]">{description}</p></article>; }
function ScoreProgress({ label, value }: { label: string; value: number }) { return <div className="mt-3 h-2.5 overflow-hidden rounded-full bg-[#dfe9f8]" role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value}><div className="h-full rounded-full bg-[#0058bc]" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
function ScoreStatus({ value }: { value: number }) { const label = value >= 85 ? "Excellent" : value >= 70 ? "Good" : value >= 50 ? "Needs Attention" : "Incomplete"; return <span className="inline-flex rounded-full bg-[#e5eeff] px-3 py-1 text-xs font-extrabold text-[#0058bc]">{label}</span>; }
function readinessDescription(value: number) { return value >= 85 ? "Your Brand Brain has a strong foundation for consistent content generation." : value >= 70 ? "Your Brand Brain is ready, with a few areas that can still be improved." : value >= 50 ? "Several brand areas need refinement before generating consistent content." : "Add more brand information to improve AI-generated content."; }
function activeSources(sources: BrandBrainState["analysis"]["sources"]): Array<[string, string]> { const entries: Array<[string, string]> = [["Website", sources.websiteUrl], ["Instagram", sources.instagramUsername], ["LinkedIn", sources.linkedinPage], ["Brand Guidelines", sources.brandGuidelinesFileName], ["Company Profile", sources.companyProfileFileName], ["Product Catalogue", sources.productCatalogueFileName]]; return entries.filter(([, value]) => value.trim()); }
function AnalysisBadge({ complete }: { complete: boolean }) { return <span className={`rounded-full px-3 py-1 text-xs font-extrabold ${complete ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{complete ? "Analysis complete" : "Not analyzed"}</span>; }
function analysisStatusLabel(status: BrandBrainState["analysis"]["status"]) { return status === "complete" ? "Analysis complete" : status === "analyzing" ? "Analysis in progress" : status === "failed" ? "Analysis failed" : "Not analyzed"; }
