"use client";

import { useMemo, useState } from "react";
import { AnalyticsHeader } from "@/components/analytics/analytics-header";
import { AnalyticsKpiGrid } from "@/components/analytics/analytics-kpi-grid";
import { ChannelBreakdownDrawer, ChannelPerformance } from "@/components/analytics/channel-performance";
import { ReachEngagementChart } from "@/components/analytics/reach-engagement-chart";
import { AnalyticsFilterEmpty, AnalyticsGlobalError, AnalyticsSkeleton, AnalyticsWidgetError, AnalyticsWorkspaceEmpty } from "@/components/analytics/analytics-states";
import { TopPerformingContent } from "@/components/analytics/top-performing-content";
import { buildAnalyticsCsv, downloadAnalyticsCsv } from "@/lib/analytics/export";
import { selectAnalyticsViewModel } from "@/lib/analytics/selectors";
import { analyticsStateScenarios, readyAnalyticsWidgetStates } from "@/lib/analytics/state-scenarios";
import type { AnalyticsContentType, AnalyticsDataSource, AnalyticsDateRangeId, AnalyticsFilters, AnalyticsPermissions, AnalyticsPlatform, AnalyticsScenario, AnalyticsWidgetKey } from "@/lib/analytics/types";

const defaultFilters: AnalyticsFilters = { dateRangeId: "7-days", brandId: "all", campaignId: "all", platform: "all", contentType: "all" };
export function AnalyticsClient({ dataSource, permissions, initialScenario = analyticsStateScenarios.ready, initialFilters = defaultFilters }: { dataSource: AnalyticsDataSource; permissions: AnalyticsPermissions; initialScenario?: AnalyticsScenario; initialFilters?: AnalyticsFilters }) {
  const [filters, setFilters] = useState(initialFilters); const [loadState, setLoadState] = useState(initialScenario.analytics); const [widgetStates, setWidgetStates] = useState(initialScenario.widgets); const [drawerOpen, setDrawerOpen] = useState(false); const [feedback, setFeedback] = useState("");
  const view = useMemo(() => selectAnalyticsViewModel(dataSource, filters, permissions), [dataSource, filters, permissions]);
  function update<K extends keyof AnalyticsFilters>(key: K, value: AnalyticsFilters[K]) { setFilters((current) => ({ ...current, [key]: value })); setFeedback(""); }
  function changeBrand(brandId: string) { setFilters((current) => ({ ...current, brandId, campaignId: "all" })); setFeedback(""); }
  function resetFilters() { setFilters(defaultFilters); setFeedback(""); }
  function retryAll() { setLoadState({ status: "ready" }); setWidgetStates({ ...readyAnalyticsWidgetStates }); }
  function retryWidget(key: AnalyticsWidgetKey) { setWidgetStates((current) => ({ ...current, [key]: { status: "ready" } })); }
  function exportData() { if (!view.currentRecords.length) return setFeedback("No analytics data is available for the selected filters."); const csv = buildAnalyticsCsv(view, dataSource, view.filters, permissions); downloadAnalyticsCsv(csv, view.periodStart, view.periodEnd); setFeedback("Analytics report exported for the active filters."); }
  return <div className="mx-auto min-w-0 w-full max-w-[1440px] px-3 py-5 min-[375px]:px-4 sm:px-6 sm:py-6 lg:px-8 lg:py-8 xl:px-10 xl:py-10"><AnalyticsHeader filters={view.filters} brands={view.brands} campaigns={view.campaigns} platforms={view.platforms} permissions={permissions} onDateRangeChange={(value: AnalyticsDateRangeId) => update("dateRangeId", value)} onBrandChange={changeBrand} onCampaignChange={(value) => update("campaignId", value)} onPlatformChange={(value: AnalyticsPlatform | "all") => update("platform", value)} onExport={exportData} />{feedback ? <p role="status" className="mt-4 rounded-lg border border-[#bfd3f2] bg-[#f4f8ff] px-4 py-3 text-sm font-semibold text-[#0b4f9c]">{feedback}</p> : null}{loadState.status === "loading" ? <AnalyticsSkeleton kpiCount={permissions.viewAnalyticsFinancialMetrics ? 4 : 3} /> : loadState.status === "error" ? <AnalyticsGlobalError message={loadState.message} onRetry={retryAll} /> : view.isWorkspaceEmpty ? <AnalyticsWorkspaceEmpty /> : <>{view.isFilterEmpty ? <AnalyticsFilterEmpty onReset={resetFilters} /> : null}{widgetStates.metrics.status === "error" ? <div className="mt-6"><AnalyticsWidgetError title="Metrics unavailable" message={widgetStates.metrics.message} onRetry={() => retryWidget("metrics")} /></div> : <AnalyticsKpiGrid kpis={view.kpis} />}<div className="mt-6 grid min-w-0 gap-6 xl:grid-cols-12"><div className="min-w-0 xl:col-span-8">{widgetStates.chart.status === "error" ? <AnalyticsWidgetError title="Performance chart unavailable" message={widgetStates.chart.message} onRetry={() => retryWidget("chart")} /> : <ReachEngagementChart series={view.series} dateRangeId={view.filters.dateRangeId} />}</div><div className="min-w-0 xl:col-span-4">{widgetStates.channels.status === "error" ? <AnalyticsWidgetError title="Channel performance unavailable" message={widgetStates.channels.message} onRetry={() => retryWidget("channels")} /> : <ChannelPerformance channels={view.channels} permissions={permissions} onOpen={() => setDrawerOpen(true)} />}</div></div>{widgetStates.content.status === "error" ? <div className="mt-6"><AnalyticsWidgetError title="Content performance unavailable" message={widgetStates.content.message} onRetry={() => retryWidget("content")} /></div> : <TopPerformingContent items={view.content} selectedContentType={view.filters.contentType} onContentTypeChange={(value: AnalyticsContentType | "all") => update("contentType", value)} />}</>}{drawerOpen ? <ChannelBreakdownDrawer channels={view.channels} permissions={permissions} onClose={() => setDrawerOpen(false)} /> : null}</div>;
}
