import Link from "next/link";
import { AnalyticsIcon } from "@/components/analytics/analytics-icon";

const block = "animate-pulse rounded bg-[#e5eaf3] motion-reduce:animate-none";
export function AnalyticsSkeleton({ kpiCount }: { kpiCount: number }) { return <div role="status" aria-live="polite" className="mt-6"><span className="sr-only">Loading analytics data.</span><div aria-hidden="true"><div className={`grid gap-4 md:grid-cols-2 ${kpiCount === 4 ? "xl:grid-cols-4" : "xl:grid-cols-3"}`}>{Array.from({ length: kpiCount }, (_, index) => <div key={index} className="min-h-44 rounded-lg border border-[#d3e4fe] bg-white p-5"><div className={`${block} h-10 w-10`} /><div className={`${block} mt-6 h-3 w-28`} /><div className={`${block} mt-3 h-9 w-24`} /></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-12"><div className="rounded-lg border border-[#d3e4fe] bg-white p-6 xl:col-span-8"><div className={`${block} h-6 w-48`} /><div className={`${block} mt-6 h-72 w-full`} /></div><div className="rounded-lg border border-[#d3e4fe] bg-white p-6 xl:col-span-4"><div className={`${block} h-6 w-40`} />{[1,2,3,4].map((item) => <div key={item} className={`${block} mt-6 h-8 w-full`} />)}</div></div><div className="mt-6 rounded-lg border border-[#d3e4fe] bg-white p-6"><div className={`${block} h-6 w-52`} /><div className={`${block} mt-6 h-56 w-full`} /></div></div></div>; }
export function AnalyticsGlobalError({ message, onRetry }: { message: string; onRetry: () => void }) { return <section role="alert" className="mt-6 rounded-lg border border-red-200 bg-white px-5 py-12 text-center"><AnalyticsIcon name="alert" className="mx-auto h-8 w-8 text-[#ba1a1a]" /><h2 className="mt-4 text-xl font-extrabold">Analytics unavailable</h2><p className="mt-2 text-sm text-[#657080]">{message}</p><button type="button" onClick={onRetry} className="mt-5 min-h-11 rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc] focus-visible:ring-offset-2">Retry analytics</button></section>; }
export function AnalyticsWorkspaceEmpty() { return <section className="mt-6 rounded-lg border border-[#d3e4fe] bg-white px-5 py-12 text-center"><h2 className="text-xl font-extrabold">No analytics data yet</h2><p className="mt-2 text-sm text-[#657080]">Performance insights will appear after content has been published.</p><Link href="/calendar" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc] focus-visible:ring-offset-2">Open Content Calendar</Link></section>; }
export function AnalyticsFilterEmpty({ onReset }: { onReset: () => void }) { return <section className="mt-6 flex flex-col gap-4 rounded-lg border border-[#bfd3f2] bg-[#f4f8ff] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-extrabold">No performance data matches these filters</h2><p className="mt-1 text-sm text-[#657080]">Try another brand, campaign, platform, or date range.</p></div><button type="button" onClick={onReset} className="min-h-10 shrink-0 rounded-lg border border-[#9fc3f4] bg-white px-4 text-sm font-bold text-[#0058bc] outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc]">Reset Filters</button></section>; }
export function AnalyticsWidgetError({ title, message, onRetry }: { title: string; message: string; onRetry: () => void }) { return <section role="alert" className="rounded-lg border border-red-200 bg-white px-5 py-10 text-center"><AnalyticsIcon name="alert" className="mx-auto h-7 w-7 text-[#ba1a1a]" /><h2 className="mt-3 text-lg font-extrabold">{title}</h2><p className="mt-2 text-sm text-[#657080]">{message}</p><button type="button" onClick={onRetry} className="mt-4 min-h-10 rounded-lg border border-[#bfd3f2] px-4 text-sm font-bold text-[#0058bc] outline-none focus-visible:ring-2 focus-visible:ring-[#0058bc]">Try again</button></section>; }
