import { BrandBrainDrawer } from "@/components/brand-brain/brand-brain-drawer";
import { formatCurrency, formatNumber, formatPercentage } from "@/lib/analytics/calculations";
import { platformLabels } from "@/lib/analytics/constants";
import type { AnalyticsPermissions, ChannelPerformance as ChannelItem } from "@/lib/analytics/types";

export function ChannelPerformance({ channels, permissions, onOpen }: { channels: ChannelItem[]; permissions: AnalyticsPermissions; onOpen: () => void }) {
  return <section className="min-w-0 rounded-lg border border-[#d3e4fe]/80 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-extrabold text-[#0b1c30]">Channel Performance</h2><p className="mt-1 text-sm leading-6 text-[#657080]">Budget share compared with conversion share.</p>{channels.length ? <div className="mt-6 grid gap-5">{channels.map((channel) => <div key={channel.platform}><div className="mb-2 text-sm font-extrabold text-[#0b1c30]">{platformLabels[channel.platform]}</div><ChannelBar channel={platformLabels[channel.platform]} label="Budget Share" value={channel.budgetShare} tone="bg-[#8ab8f5]" /><ChannelBar channel={platformLabels[channel.platform]} label="Conversion Share" value={channel.conversionShare} tone="bg-[#4648d4]" /></div>)}</div> : <p className="mt-8 rounded-lg bg-[#f8faff] px-4 py-10 text-center text-sm text-[#657080]">No channel data for this selection.</p>}{channels.length && permissions.viewChannelBreakdown ? <button type="button" onClick={onOpen} className="mt-6 min-h-11 w-full rounded-lg border border-[#bfd3f2] px-4 text-sm font-bold text-[#0058bc] outline-none transition hover:bg-[#eff4ff] focus-visible:ring-2 focus-visible:ring-[#0058bc]">View Channels Breakdown</button> : null}</section>;
}
function ChannelBar({ channel, label, value, tone }: { channel: string; label: string; value: number; tone: string }) { const percentage = Math.max(0, Math.min(100, value)); return <div className="mt-2"><div className="flex items-center justify-between gap-3 text-xs font-semibold text-[#526174]"><span>{label}</span><span>{formatPercentage(percentage)}</span></div><div role="progressbar" aria-label={`${channel} ${label}: ${formatPercentage(percentage)}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(percentage)} className="mt-1.5 h-2 overflow-hidden rounded-full bg-[#e5eeff]"><div className={`h-full rounded-full ${tone}`} style={{ width: `${percentage}%` }} /></div></div>; }

export function ChannelBreakdownDrawer({ channels, permissions, onClose }: { channels: ChannelItem[]; permissions: AnalyticsPermissions; onClose: () => void }) {
  return <BrandBrainDrawer title="Channels Breakdown" description="Read-only channel metrics for the active analytics filters." onClose={onClose}><div className="grid gap-4 p-5 sm:p-7">{channels.map((channel) => <article key={channel.platform} className="rounded-lg border border-[#d3e4fe] p-4"><h3 className="text-base font-extrabold text-[#0b1c30]">{platformLabels[channel.platform]}</h3><dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 sm:grid-cols-3">{permissions.viewAnalyticsFinancialMetrics ? <Metric label="Spend" value={formatCurrency(channel.spend)} /> : null}<Metric label="Reach" value={formatNumber(channel.reach)} /><Metric label="Impressions" value={formatNumber(channel.impressions)} /><Metric label="Engagement" value={formatNumber(channel.engagement)} /><Metric label="Engagement Rate" value={formatPercentage(channel.engagementRate)} /><Metric label="Clicks" value={formatNumber(channel.clicks)} /><Metric label="Conversions" value={formatNumber(channel.conversions)} /><Metric label="Conversion Rate" value={formatPercentage(channel.conversionRate)} />{permissions.viewAnalyticsFinancialMetrics ? <Metric label="ROAS" value={`${channel.roas.toFixed(2)}x`} /> : null}</dl></article>)}</div></BrandBrainDrawer>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-[11px] font-extrabold uppercase tracking-[.08em] text-[#657080]">{label}</dt><dd className="mt-1 break-words text-sm font-bold text-[#0b1c30]">{value}</dd></div>; }
