"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ResponsiveOverlayShell } from "@/components/ui/responsive-overlay-shell";
import type { WorkspaceAsset } from "@/lib/assets/types";

export function AssetPickerDialog({ assets, mode, selectedIds, maximum = 3, onClose, onSave }: { assets: WorkspaceAsset[]; mode: "core" | "logo"; selectedIds: string[]; maximum?: number; onClose: () => void; onSave: (ids: string[]) => void }) {
  const [selection, setSelection] = useState(selectedIds);
  const [query, setQuery] = useState("");
  const eligible = useMemo(() => assets.filter((asset) => mode === "logo" ? asset.kind === "logo" : ["image", "logo", "generated"].includes(asset.kind)).filter((asset) => !query.trim() || asset.name.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [assets, mode, query]);
  function toggle(id: string) { if (mode === "logo") return setSelection([id]); setSelection((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < maximum ? [...current, id] : current); }
  const title = mode === "logo" ? "Select Brand Logo" : "Select Core Brand Assets";
  const footer = <><Link href="/assets" className="inline-flex min-h-11 items-center justify-center rounded-lg border border-[#0058bc] px-4 text-sm font-bold text-[#0058bc]">Open Asset Library</Link><button type="button" onClick={onClose} className="min-h-11 rounded-lg border border-[#c5d2e5] px-4 text-sm font-bold">Cancel</button><button type="button" disabled={!selection.length} onClick={() => onSave(selection)} className="min-h-11 rounded-lg bg-[#0058bc] px-5 text-sm font-bold text-white disabled:bg-[#aab8ca]">Use Selected Asset{mode === "core" && selection.length !== 1 ? "s" : ""}</button></>;
  return <ResponsiveOverlayShell title={title} description={mode === "logo" ? "Choose a logo already stored in the workspace Asset Library." : `Choose up to ${maximum} existing visual files. Uploads are managed only in Asset Library.`} footer={footer} maxWidth="max-w-[960px]" onClose={onClose}><div className="grid gap-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Asset Library" className="h-11 w-full rounded-lg border border-[#c5d2e5] px-3 text-sm outline-none focus:ring-2 focus:ring-blue-100 sm:max-w-sm" /><p className="text-xs font-bold text-[#657080]">{selection.length} of {mode === "logo" ? 1 : maximum} selected</p></div>{eligible.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{eligible.map((asset) => { const active = selection.includes(asset.id); const disabled = !active && mode === "core" && selection.length >= maximum; return <button key={asset.id} type="button" disabled={disabled} aria-pressed={active} onClick={() => toggle(asset.id)} className={`overflow-hidden rounded-xl border text-left outline-none transition focus-visible:ring-2 focus-visible:ring-[#0058bc] disabled:cursor-not-allowed disabled:opacity-50 ${active ? "border-[#0058bc] bg-[#eff4ff] ring-2 ring-blue-100" : "border-[#d3e4fe] bg-white"}`}><span className="relative block aspect-[16/10] bg-[#eff4ff]">{asset.previewUrl ? <Image src={asset.previewUrl} alt={asset.name} fill unoptimized className={asset.kind === "logo" ? "object-contain p-4" : "object-cover"} /> : null}</span><span className="block p-3"><span className="block truncate text-sm font-extrabold">{asset.name}</span><span className="mt-1 block truncate text-xs text-[#657080]">{asset.fileName}</span></span></button>; })}</div> : <div className="rounded-xl border-2 border-dashed p-10 text-center"><p className="font-extrabold">No eligible assets found.</p><p className="mt-2 text-sm text-[#657080]">Upload the file from Asset Library first.</p></div>}</div></ResponsiveOverlayShell>;
}
