import type { WorkspaceAsset } from "@/lib/assets/types";

const coffeeBeans = "https://lh3.googleusercontent.com/aida-public/AB6AXuBXaPfHNhCGII6FOB-bAUyFQYQ7afrWP6VeREebGZXI6rvHG7tN4OyWBdtSYVy3ogAC4V5NeL9N0AMYECnmsfUQXRpvZgb2KFP-q35G78cUVDfeGAk1QVgt4d_UgB6WgNw9I9V3TtQmtmCCmesL4vJg8V_QI4ovtFjLCZJlwLJj89xCz6feBRG9GnRcwnWy5bg6cbMB4SS249dZrI1vfQlGTHLmCd25-9ljkID1P73ZyQFU-g_7Ds61";
const ceramicMug = "https://lh3.googleusercontent.com/aida-public/AB6AXuCLaCQ1KCRiF8l--45Fz4VFlVCExRYqKlReiII2QsVWTA_MTdcLi3fwNp3x6a4dkNXEWTsYngKb4NAuUaFlmrMxFz0dyRLEVRP_ym0sPPOiYWXqY4Yah4Se5CxnAxkGKv25O2p3ymtV35CKES8V_FuDV2jhAyrq0H3ySu_AeuB6scV6HZ_dC5khyrjpW37tj9J-UMcIvLwjsxpluWve6ANrKaURW-2NkYhRYhoCtZsQziLWSIz7DQwE";
const coffeeShop = "https://lh3.googleusercontent.com/aida-public/AB6AXuBGVc2YXf_R5hCspI-jCLdk8ax3pgdLSaFTLqJwf5TXfUmmpQBLtgMb4qQ1xIpFpmoDAXX2lNf8clQ1tUjR2vKYcqKVWlpOXIPWtTC4fRLlGDwkDILD7ceBiwNgT1SyQrPPZ_8tcRAr4undRinzKsBoPfxtXISKaFrS2Wy9SLHecmh-TUz7Z0uTXdvF0XYr0ObZVOiahBlY1HCvN2NWeQQ8g04afwjAF4ymOxGxdrX5_s86kNtgjH0B";
const logo = "https://lh3.googleusercontent.com/aida-public/AB6AXuBuvwxHG-3aEQmbB3JVSbYYqCSmYs7mE3kB2z6pD7ZaBXEQWjPcSZ6MJemSSul7V5oSl9OiQTMHsjxqPBu3bdYF2xK6x7vmHAWAARG3T0aW665qff9bd7YUOZLBKML8CltnKMDwcr1uukBdhB5LiF79v340gUTFtuxk_DI1h7YmnqG3PssQD1RH2_mxk68KIl5fCekqUZs0SMAj-9PpO9SK67dlkFEchi3cHPdEY0acXCF08HHpREN-";

const base = { description: "", brandIds: ["brand-coffee-xyz"], campaignIds: [] as string[], createdAt: "2026-07-08T09:00:00+07:00", updatedAt: "2026-07-11T09:10:00+07:00" };

export const assetLibraryMockData: WorkspaceAsset[] = [
  { ...base, id: "logo-primary", name: "Coffee XYZ Primary Logo", fileName: "coffee_xyz_primary.svg", mimeType: "image/svg+xml", kind: "logo", source: "logo-render", previewUrl: logo, tags: ["logo", "primary"], sizeBytes: 184320, usage: [{ type: "brand-logo", entityId: "brand-coffee-xyz", label: "Coffee XYZ brand logo" }, { type: "logo-output", entityId: "logo-render-primary", label: "Primary logo render" }] },
  { ...base, id: "asset-coffee-beans", name: "Organic Coffee Beans", fileName: "organic-coffee-beans.jpg", mimeType: "image/jpeg", kind: "image", source: "upload", previewUrl: coffeeBeans, description: "Organic coffee beans for product and educational content.", tags: ["coffee", "beans", "premium"], sizeBytes: 2480000, campaignIds: ["campaign-education-series"], usage: [{ type: "brand-core", entityId: "brand-coffee-xyz", label: "Coffee XYZ core visual" }, { type: "campaign", entityId: "campaign-education-series", label: "Education Series" }] },
  { ...base, id: "asset-ceramic-mug", name: "Reusable Ceramic Mug", fileName: "coffee-xyz-mug.jpg", mimeType: "image/jpeg", kind: "image", source: "upload", previewUrl: ceramicMug, description: "Reusable ceramic mug product photo.", tags: ["mug", "product", "sustainable"], sizeBytes: 1920000, campaignIds: ["campaign-july-promotion"], usage: [{ type: "brand-core", entityId: "brand-coffee-xyz", label: "Coffee XYZ core visual" }, { type: "calendar", entityId: "post-mug-july", label: "July Promotion scheduled post" }] },
  { ...base, id: "asset-coffee-shop", name: "Coffee Shop Interior", fileName: "coffee-xyz-store.jpg", mimeType: "image/jpeg", kind: "image", source: "upload", previewUrl: coffeeShop, description: "Modern eco-conscious Coffee XYZ shop interior.", tags: ["store", "interior", "lifestyle"], sizeBytes: 3160000, usage: [{ type: "brand-core", entityId: "brand-coffee-xyz", label: "Coffee XYZ core visual" }] },
  { ...base, id: "asset-ai-summer", name: "Summer Wellness Hero", fileName: "ai-summer-wellness.webp", mimeType: "image/webp", kind: "generated", source: "ai-generation", previewUrl: ceramicMug, description: "AI-generated campaign hero visual.", tags: ["ai", "campaign", "hero"], sizeBytes: 1320000, brandIds: ["brand-skincare-abc"], campaignIds: ["campaign-summer-wellness"], usage: [{ type: "ai-output", entityId: "generation-summer-hero", label: "AI image generation" }, { type: "campaign", entityId: "campaign-summer-wellness", label: "Summer Wellness" }] },
  { ...base, id: "asset-guidelines", name: "Coffee XYZ Visual Guidelines", fileName: "coffee-xyz-visual-guidelines.pdf", mimeType: "application/pdf", kind: "document", source: "upload", previewUrl: "", description: "Visual identity and layout guidelines.", tags: ["guidelines", "brand"], sizeBytes: 4860000, usage: [] },
];
