import type { CalendarState, ContentIdea, ContentPillar, ContentVersion } from "@/lib/calendar/types";

export const contentPillars: ContentPillar[] = [
  { id: "education", name: "Education", color: "#2563EB", description: "Practical knowledge that builds audience confidence." },
  { id: "product", name: "Product", color: "#7C3AED", description: "Products, benefits, and ways to enjoy them." },
  { id: "promotion", name: "Promotion", color: "#DC2626", description: "Timely offers and conversion-focused content." },
  { id: "lifestyle", name: "Lifestyle", color: "#059669", description: "Coffee moments, rituals, and community." },
  { id: "sustainability", name: "Sustainability", color: "#0F766E", description: "Responsible sourcing and lower-impact choices." },
  { id: "customer-stories", name: "Customer Stories", color: "#C2410C", description: "Customer experiences and social proof." },
  { id: "behind-the-scenes", name: "Behind the Scenes", color: "#4F46E5", description: "People and processes behind the brand." },
];

export const contentIdeas: ContentIdea[] = [
  { id: "idea-coffee-brewing", title: "Coffee Brewing Basics", coreTopic: "A repeatable home-brewing method", pillarId: "education", objective: "educate", targetAudience: "New home brewers", mainMessage: "Great coffee starts with a few controllable basics.", campaignId: "cmp-july-awareness", creationSource: "manual", createdAt: "2026-07-01T08:00:00+07:00", updatedAt: "2026-07-01T08:00:00+07:00" },
  { id: "idea-monday-brew", title: "Monday Brew", coreTopic: "A calm start to the work week", pillarId: "lifestyle", objective: "engage", targetAudience: "Young professionals", mainMessage: "A good Monday begins with an intentional coffee ritual.", creationSource: "template", createdAt: "2026-07-01T08:10:00+07:00", updatedAt: "2026-07-01T08:10:00+07:00" },
  { id: "idea-quick-tips", title: "Quick Coffee Tips", coreTopic: "Small adjustments for better flavor", pillarId: "education", objective: "educate", targetAudience: "Everyday coffee drinkers", mainMessage: "Simple changes can noticeably improve every cup.", creationSource: "ai", createdAt: "2026-07-01T08:20:00+07:00", updatedAt: "2026-07-01T08:20:00+07:00" },
  { id: "idea-latte-art", title: "Latte Art Guide", coreTopic: "Pouring a beginner heart", pillarId: "education", objective: "educate", targetAudience: "Aspiring home baristas", mainMessage: "Good milk texture makes latte art approachable.", creationSource: "repurposed", createdAt: "2026-07-01T08:30:00+07:00", updatedAt: "2026-07-01T08:30:00+07:00" },
  { id: "idea-mid-month-offer", title: "Mid-Month Offer", coreTopic: "Coffee and pastry bundle", pillarId: "promotion", objective: "sell", targetAudience: "Nearby office workers", mainMessage: "Take a better afternoon break for less.", campaignId: "cmp-weekend-promo", creationSource: "manual", createdAt: "2026-07-01T08:40:00+07:00", updatedAt: "2026-07-01T08:40:00+07:00" },
  { id: "idea-weekend-vibe", title: "Weekend Coffee Vibe", coreTopic: "Slow weekend moments at the cafe", pillarId: "lifestyle", objective: "engage", targetAudience: "Coffee-loving communities", mainMessage: "Make room for a slower cup this weekend.", creationSource: "brand-asset", createdAt: "2026-07-01T08:50:00+07:00", updatedAt: "2026-07-01T08:50:00+07:00" },
  { id: "idea-meet-barista", title: "Meet Our Barista", coreTopic: "The person behind each cup", pillarId: "behind-the-scenes", objective: "inform", targetAudience: "Existing customers", mainMessage: "Craft and care are built into every order.", creationSource: "manual", createdAt: "2026-07-01T09:00:00+07:00", updatedAt: "2026-07-01T09:00:00+07:00" },
  { id: "idea-sustainable-packaging", title: "Sustainable Coffee Packaging", coreTopic: "Why the brand changed its packaging", pillarId: "sustainability", objective: "inform", targetAudience: "Eco-conscious coffee buyers", mainMessage: "Better packaging can protect coffee and reduce impact.", creationSource: "ai", createdAt: "2026-07-01T09:10:00+07:00", updatedAt: "2026-07-01T09:10:00+07:00" },
];

export const contentVersions: ContentVersion[] = [
  { id: "version-brewing-instagram", contentIdeaId: "idea-coffee-brewing", platform: "instagram", assetType: "carousel", headline: "Coffee Brewing Basics", caption: "Dial in the basics before buying more equipment.", cta: "Save this guide", hashtags: ["coffee", "brewing"], visualBrief: "Clean instructional carousel with brewing tools.", publishDate: "2026-07-04", publishTime: "09:00", timezone: "Asia/Jakarta", status: "scheduled", createdBy: "Wanda", createdAt: "2026-07-01T08:00:00+07:00", updatedAt: "2026-07-01T08:00:00+07:00" },
  { id: "version-brewing-facebook", contentIdeaId: "idea-coffee-brewing", platform: "facebook", assetType: "carousel", headline: "A Better Framework for Brewing Coffee", caption: "Consistency comes from controlling the variables that matter.", cta: "Share with your team", hashtags: ["coffeeeducation", "hospitality"], publishDate: "2026-07-04", publishTime: "11:30", timezone: "Asia/Jakarta", status: "ready", createdBy: "Wanda", createdAt: "2026-07-01T08:05:00+07:00", updatedAt: "2026-07-01T08:05:00+07:00" },
  { id: "version-monday-instagram", contentIdeaId: "idea-monday-brew", platform: "instagram", assetType: "reel", headline: "Monday Brew Ritual", caption: "A small ritual for a clearer Monday.", cta: "Tag your Monday coffee friend", hashtags: ["mondaybrew", "coffeeritual"], publishDate: "2026-07-06", publishTime: "07:30", timezone: "Asia/Jakarta", status: "published", createdBy: "Mika", createdAt: "2026-07-01T08:10:00+07:00", updatedAt: "2026-07-06T07:31:00+07:00" },
  { id: "version-monday-tiktok", contentIdeaId: "idea-monday-brew", platform: "tiktok", assetType: "short-video", headline: "POV: Monday Needs Coffee", caption: "Reset the Monday mood in fifteen seconds.", cta: "Follow for more coffee rituals", hashtags: ["coffeetok", "mondaymood"], publishDate: "2026-07-06", publishTime: "08:00", timezone: "Asia/Jakarta", status: "published", createdBy: "Mika", createdAt: "2026-07-01T08:15:00+07:00", updatedAt: "2026-07-06T08:01:00+07:00" },
  { id: "version-tips-instagram", contentIdeaId: "idea-quick-tips", platform: "instagram", assetType: "story", headline: "Three Quick Coffee Fixes", caption: "Three fixes you can try before your next brew.", cta: "Reply with your result", hashtags: ["coffeetips"], publishDate: "2026-07-10", publishTime: "09:15", timezone: "Asia/Jakarta", status: "scheduled", createdBy: "Ari", createdAt: "2026-07-01T08:20:00+07:00", updatedAt: "2026-07-01T08:20:00+07:00" },
  { id: "version-tips-tiktok", contentIdeaId: "idea-quick-tips", platform: "tiktok", assetType: "short-video", headline: "Fix Bitter Coffee Fast", caption: "Try these adjustments before blaming the beans.", cta: "Save for tomorrow morning", hashtags: ["coffeetips", "homebarista"], publishDate: "2026-07-10", publishTime: "12:00", timezone: "Asia/Jakarta", status: "ready", createdBy: "Ari", createdAt: "2026-07-01T08:25:00+07:00", updatedAt: "2026-07-01T08:25:00+07:00" },
  { id: "version-latte-instagram", contentIdeaId: "idea-latte-art", platform: "instagram", assetType: "carousel", headline: "Your First Latte Art Heart", caption: "Texture first, pour second.", cta: "Save the pouring steps", hashtags: ["latteart", "homebarista"], publishDate: "2026-07-10", publishTime: "15:00", timezone: "Asia/Jakarta", status: "draft", createdBy: "Nina", createdAt: "2026-07-01T08:30:00+07:00", updatedAt: "2026-07-01T08:30:00+07:00" },
  { id: "version-latte-youtube", contentIdeaId: "idea-latte-art", platform: "youtube", assetType: "tutorial-video", headline: "Beginner Latte Art Tutorial", caption: "A full walkthrough from steaming to finishing the heart.", cta: "Subscribe for the next technique", hashtags: ["lattearttutorial"], publishDate: "2026-07-10", publishTime: "18:30", timezone: "Asia/Jakarta", status: "failed", createdBy: "Nina", createdAt: "2026-07-01T08:35:00+07:00", updatedAt: "2026-07-10T18:31:00+07:00" },
  { id: "version-offer-facebook", contentIdeaId: "idea-mid-month-offer", platform: "facebook", assetType: "promo-image", headline: "Mid-Month Coffee Break", caption: "Pair your afternoon coffee with a pastry this week.", cta: "Visit us before 5 PM", hashtags: ["coffeeoffer", "jakartacafe"], publishDate: "2026-07-16", publishTime: "10:00", timezone: "Asia/Jakarta", status: "scheduled", createdBy: "Wanda", createdAt: "2026-07-01T08:40:00+07:00", updatedAt: "2026-07-01T08:40:00+07:00" },
  { id: "version-vibe-instagram", contentIdeaId: "idea-weekend-vibe", platform: "instagram", assetType: "reel", headline: "Weekend Coffee Vibe", caption: "Slow down and stay for another cup.", cta: "Share your weekend ritual", hashtags: ["weekendcoffee", "cafevibes"], publishDate: "2026-07-25", publishTime: "09:30", timezone: "Asia/Jakarta", status: "ready", createdBy: "Mika", createdAt: "2026-07-01T08:50:00+07:00", updatedAt: "2026-07-01T08:50:00+07:00" },
  { id: "version-barista-youtube", contentIdeaId: "idea-meet-barista", platform: "youtube", assetType: "community-post", headline: "Meet the Craft Behind the Cup", caption: "Meet the teammate who turns daily repetition into dependable quality.", cta: "Meet the rest of our team", hashtags: ["peopleandculture", "coffee"], publishDate: "2026-07-21", publishTime: "13:00", timezone: "Asia/Jakarta", status: "draft", createdBy: "Ari", createdAt: "2026-07-01T09:00:00+07:00", updatedAt: "2026-07-01T09:00:00+07:00" },
  { id: "version-packaging-instagram", contentIdeaId: "idea-sustainable-packaging", platform: "instagram", assetType: "carousel", headline: "A Better Bag for Better Coffee", caption: "Our packaging decision balances freshness and lower impact.", cta: "Learn about the materials", hashtags: ["sustainablecoffee", "packaging"], publishDate: "2026-07-29", publishTime: "10:30", timezone: "Asia/Jakarta", status: "scheduled", createdBy: "Wanda", createdAt: "2026-07-01T09:10:00+07:00", updatedAt: "2026-07-01T09:10:00+07:00" },
];

export const initialCalendarState: CalendarState = {
  view: "month",
  currentDate: "2026-07-01",
  postDetailDrawerOpen: false,
  filters: { platform: "all", pillarId: "all", status: "all", createdBy: "all" },
  pillars: contentPillars,
  ideas: contentIdeas,
  versions: contentVersions,
};
