import type { UnscheduledIdea } from "@/lib/calendar/unscheduled-idea-types";
export const initialUnscheduledIdeas: UnscheduledIdea[] = [
  { id:"unscheduled-beans",title:"How to Choose Coffee Beans",coreTopic:"Matching beans to brewing methods",pillarId:"education",objective:"educate",targetAudience:"New home brewers",mainMessage:"The right beans make brewing easier.",suggestedPlatform:"instagram",suggestedAssetType:"carousel",source:"manual",creationSource:"manual",notes:"Include roast-level examples.",createdAt:"2026-07-01T08:00:00+07:00",updatedAt:"2026-07-10T08:00:00+07:00" },
  { id:"unscheduled-morning",title:"Morning Coffee Ritual",coreTopic:"A calmer morning routine",pillarId:"lifestyle",objective:"engage",targetAudience:"Young professionals",mainMessage:"A small ritual can reset the morning.",suggestedPlatform:"tiktok",suggestedAssetType:"short-video",source:"ai",creationSource:"ai",createdAt:"2026-07-02T08:00:00+07:00",updatedAt:"2026-07-09T08:00:00+07:00" },
  { id:"unscheduled-roasting",title:"Meet the Roasting Team",coreTopic:"People behind the roast",pillarId:"behind-the-scenes",objective:"inform",targetAudience:"Existing customers",mainMessage:"Every roast is guided by experienced people.",suggestedPlatform:"linkedin",suggestedAssetType:"image-post",source:"campaign",creationSource:"manual",campaignId:"cmp-july-awareness",createdAt:"2026-07-03T08:00:00+07:00",updatedAt:"2026-07-08T08:00:00+07:00" },
  { id:"unscheduled-cold-brew",title:"Cold Brew Starter Guide",coreTopic:"Making balanced cold brew",pillarId:"product",objective:"educate",targetAudience:"Coffee experimenters",mainMessage:"Cold brew is approachable with the right ratio.",suggestedPlatform:"youtube",suggestedAssetType:"long-video",source:"ai",creationSource:"ai",createdAt:"2026-07-04T08:00:00+07:00",updatedAt:"2026-07-07T08:00:00+07:00" },
  { id:"unscheduled-customer",title:"Customer Coffee Setup",coreTopic:"A real home coffee corner",pillarId:"customer-stories",objective:"engage",targetAudience:"Home coffee community",mainMessage:"Real setups inspire achievable improvements.",source:"brand-brain",creationSource:"brand-asset",createdAt:"2026-07-05T08:00:00+07:00",updatedAt:"2026-07-06T08:00:00+07:00" },
  { id:"unscheduled-waste",title:"Reducing Packaging Waste",coreTopic:"Lower-impact coffee packaging",pillarId:"sustainability",objective:"inform",targetAudience:"Eco-conscious customers",mainMessage:"Packaging choices can reduce everyday waste.",suggestedPlatform:"facebook",suggestedAssetType:"image-post",source:"manual",creationSource:"repurposed",createdAt:"2026-07-06T08:00:00+07:00",updatedAt:"2026-07-05T08:00:00+07:00" },
];
